// Authentication Screen Styles (Login & Register)
import { colors, borderRadius } from './theme';

export const authStyles = {
  loginContainer: {
    width: '100%',
    maxWidth: '400px',
    margin: '0 auto',
  },
  loginTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: '32px',
    textAlign: 'center',
  },
  loginButton: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  loginButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  loginButtonDisabled: {
    backgroundColor: colors.gray400,
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  sendOtpButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '8px',
    border: 'none',
    cursor: 'pointer',
  },
  sendOtpButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  sendOtpButtonDisabled: {
    backgroundColor: colors.gray400,
    cursor: 'not-allowed',
  },
  resendButton: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '8px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.primary,
    cursor: 'pointer',
  },
  resendButtonText: {
    color: colors.primary,
    fontSize: '14px',
    fontWeight: '600',
  },
  demoLoginButton: {
    width: '100%',
    backgroundColor: '#10b981',
    paddingTop: '14px',
    paddingBottom: '14px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '24px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 8px rgba(16, 185, 129, 0.3)',
  },
  demoLoginButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  demoLoginButtonDisabled: {
    backgroundColor: colors.gray400,
    boxShadow: 'none',
    cursor: 'not-allowed',
  },
  loginMethodToggle: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    backgroundColor: colors.gray100,
    borderRadius: borderRadius.md,
    padding: '4px',
    marginBottom: '24px',
  },
  toggleButton: {
    flex: 1,
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.sm,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    border: 'none',
    backgroundColor: 'transparent',
  },
  toggleButtonActive: {
    backgroundColor: colors.white,
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  toggleButtonText: {
    fontSize: '14px',
    fontWeight: '600',
    color: colors.gray700,
  },
  toggleButtonTextActive: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  demoCredentialsContainer: {
    width: '100%',
    backgroundColor: '#EFF6FF',
    padding: '16px',
    borderRadius: borderRadius.md,
    marginBottom: '16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#3B82F6',
  },
  demoCredentialsText: {
    fontSize: '13px',
    color: '#1E40AF',
    textAlign: 'center',
    lineHeight: '20px',
    fontWeight: '500',
  },
  signUpContainer: {
    marginTop: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  signUpText: {
    fontSize: '14px',
    color: colors.textLight,
    opacity: 0.8,
  },
  signUpLink: {
    fontSize: '14px',
    fontWeight: '500',
    color: colors.primary,
    cursor: 'pointer',
    textDecoration: 'none',
  },
  // Register Screen Styles
  registerContainer: {
    width: '100%',
    maxWidth: '400px',
    margin: '0 auto',
  },
  registerInput: {
    width: '100%',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    paddingRight: '16px',
    backgroundColor: colors.backgroundLight,
    color: colors.contentLight,
    borderRadius: borderRadius.lg,
    fontSize: '16px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.subtleLight,
    outline: 'none',
    boxSizing: 'border-box',
  },
  registerButton: {
    width: '100%',
    backgroundColor: colors.primary,
    color: colors.white,
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '20px',
    paddingRight: '20px',
    borderRadius: borderRadius.lg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 8px rgba(6, 66, 156, 0.3)',
    fontSize: '16px',
    fontWeight: 'bold',
  },
  registerButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  registerButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  legalContainer: {
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  legalText: {
    fontSize: '12px',
    color: colors.contentLight,
    opacity: 0.7,
    textAlign: 'center',
    lineHeight: '16px',
  },
  legalLink: {
    fontSize: '12px',
    fontWeight: '600',
    color: colors.primary,
    cursor: 'pointer',
    textDecoration: 'none',
  },
  searchButton: {
    backgroundColor: colors.accent,
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '24px',
    paddingRight: '24px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '16px',
    border: 'none',
    cursor: 'pointer',
  },
  searchButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: '600',
  },
  apiTestButton: {
    backgroundColor: colors.gray500,
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '24px',
    paddingRight: '24px',
    borderRadius: borderRadius.md,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '16px',
    border: 'none',
    cursor: 'pointer',
  },
  apiTestButtonText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: '600',
  },
};


