// Cart Page Styles - E-commerce Design
import { colors, borderRadius, spacing } from './theme';

// Re-export colors for convenience
export { colors };

export const cartStyles = {
  cartPageContainer: {
    paddingTop: '70px', // Account for fixed top navigation
    minHeight: '100vh',
    backgroundColor: colors.backgroundLight,
  },
  cartPageHeader: {
    backgroundColor: colors.white,
    borderBottom: `1px solid ${colors.borderLight}`,
    padding: '24px 0',
    marginBottom: '24px',
  },
  cartPageHeaderContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartPageTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: 0,
  },
  cartItemCount: {
    fontSize: '16px',
    color: colors.textSecondary,
    margin: 0,
  },
  cartContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px 40px',
    display: 'grid',
    gridTemplateColumns: '1fr 380px',
    gap: '24px',
  },
  cartItemsSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  cartItemsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `2px solid ${colors.borderLight}`,
  },
  cartItemsTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: 0,
  },
  clearCartButton: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.gray400}`,
    color: colors.textSecondary,
    padding: '8px 16px',
    borderRadius: borderRadius.md,
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  clearCartButtonHover: {
    backgroundColor: colors.gray100,
    borderColor: colors.gray400,
  },
  cartItem: {
    display: 'flex',
    gap: '20px',
    padding: '20px 0',
    borderBottom: `1px solid ${colors.borderLight}`,
  },
  cartItemLast: {
    borderBottom: 'none',
  },
  cartItemImage: {
    width: '120px',
    height: '160px',
    borderRadius: borderRadius.md,
    objectFit: 'cover',
    backgroundColor: colors.gray100,
    flexShrink: 0,
  },
  cartItemImagePlaceholder: {
    width: '120px',
    height: '160px',
    borderRadius: borderRadius.md,
    backgroundColor: colors.gray100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '48px',
    color: colors.gray400,
    flexShrink: 0,
  },
  cartItemDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  cartItemCategory: {
    marginBottom: '4px',
  },
  cartItemCategoryBadge: {
    display: 'inline-block',
    padding: '4px 12px',
    borderRadius: borderRadius.sm,
    fontSize: '12px',
    fontWeight: '600',
    backgroundColor: colors.gray100,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  cartItemCategoryBadgeMandatory: {
    backgroundColor: colors.primary,
    color: colors.white,
  },
  cartItemTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
    lineHeight: '1.4',
  },
  cartItemPriceInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  cartItemPriceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '14px',
  },
  cartItemPriceLabel: {
    color: colors.textSecondary,
  },
  cartItemPriceValue: {
    color: colors.primary,
    fontWeight: '600',
  },
  cartItemActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginTop: 'auto',
  },
  quantityControl: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    border: `1px solid ${colors.borderLight}`,
    borderRadius: borderRadius.md,
    padding: '4px',
  },
  quantityButton: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: borderRadius.sm,
    cursor: 'pointer',
    fontSize: '18px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    transition: 'all 0.2s ease',
  },
  quantityButtonHover: {
    backgroundColor: colors.gray100,
  },
  quantityButtonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  quantityValue: {
    minWidth: '40px',
    textAlign: 'center',
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
  },
  removeButton: {
    backgroundColor: 'transparent',
    border: `1px solid ${colors.gray400}`,
    color: colors.textSecondary,
    padding: '8px 16px',
    borderRadius: borderRadius.md,
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  removeButtonHover: {
    backgroundColor: '#fee2e2',
    borderColor: '#ef4444',
    color: '#dc2626',
  },
  cartSummary: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    height: 'fit-content',
    position: 'sticky',
    top: '90px',
  },
  cartSummaryTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 20px 0',
    paddingBottom: '16px',
    borderBottom: `2px solid ${colors.borderLight}`,
  },
  cartSummaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
    fontSize: '16px',
  },
  cartSummaryLabel: {
    color: colors.textSecondary,
  },
  cartSummaryValue: {
    color: colors.textPrimary,
    fontWeight: '500',
  },
  cartSummaryTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: `2px solid ${colors.borderLight}`,
    fontSize: '20px',
    fontWeight: 'bold',
  },
  cartSummaryTotalLabel: {
    color: colors.textPrimary,
  },
  cartSummaryTotalValue: {
    color: colors.primary,
    fontSize: '24px',
  },
  checkoutButton: {
    width: '100%',
    padding: '16px',
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: borderRadius.md,
    fontSize: '18px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '24px',
    transition: 'all 0.2s ease',
  },
  checkoutButtonHover: {
    backgroundColor: '#053080',
    transform: 'scale(1.02)',
  },
  checkoutButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  emptyCart: {
    textAlign: 'center',
    padding: '80px 20px',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  emptyCartIcon: {
    fontSize: '80px',
    marginBottom: '24px',
  },
  emptyCartTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 12px 0',
  },
  emptyCartText: {
    fontSize: '16px',
    color: colors.textSecondary,
    margin: '0 0 32px 0',
  },
  continueShoppingButton: {
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    padding: '12px 32px',
    borderRadius: borderRadius.md,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  continueShoppingButtonHover: {
    backgroundColor: '#053080',
    transform: 'scale(1.05)',
  },
};

