// Checkout Page Styles - E-commerce Design
import { colors, borderRadius, spacing } from './theme';

// Re-export colors for convenience
export { colors };

export const checkoutStyles = {
  checkoutPageContainer: {
    paddingTop: '70px', // Account for fixed top navigation
    minHeight: '100vh',
    backgroundColor: colors.backgroundLight,
  },
  checkoutPageHeader: {
    backgroundColor: colors.white,
    borderBottom: `1px solid ${colors.borderLight}`,
    padding: '24px 0',
    marginBottom: '24px',
  },
  checkoutPageHeaderContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
  },
  checkoutPageTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: 0,
  },
  checkoutContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px 40px',
    display: 'grid',
    gridTemplateColumns: '1fr 400px',
    gap: '24px',
  },
  checkoutMain: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  checkoutSection: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  checkoutSectionTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 20px 0',
    paddingBottom: '16px',
    borderBottom: `2px solid ${colors.borderLight}`,
  },
  orderItemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginBottom: '24px',
  },
  orderItem: {
    display: 'flex',
    gap: '16px',
    padding: '16px',
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
  },
  orderItemImage: {
    width: '80px',
    height: '100px',
    borderRadius: borderRadius.md,
    objectFit: 'cover',
    backgroundColor: colors.gray100,
    flexShrink: 0,
  },
  orderItemImagePlaceholder: {
    width: '80px',
    height: '100px',
    borderRadius: borderRadius.md,
    backgroundColor: colors.gray100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    color: colors.gray400,
    flexShrink: 0,
  },
  orderItemDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  orderItemTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
    lineHeight: '1.4',
  },
  orderItemQuantity: {
    fontSize: '14px',
    color: colors.textSecondary,
  },
  orderItemPrice: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: colors.primary,
    alignSelf: 'flex-end',
  },
  priceBreakdown: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: `1px solid ${colors.borderLight}`,
  },
  priceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '16px',
  },
  priceLabel: {
    color: colors.textSecondary,
  },
  priceValue: {
    color: colors.textPrimary,
    fontWeight: '500',
  },
  priceTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '8px',
    paddingTop: '16px',
    borderTop: `2px solid ${colors.borderLight}`,
    fontSize: '20px',
    fontWeight: 'bold',
  },
  priceTotalLabel: {
    color: colors.textPrimary,
  },
  priceTotalValue: {
    color: colors.primary,
    fontSize: '24px',
  },
  infoCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px',
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.borderLight}`,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  infoCardHover: {
    backgroundColor: colors.gray100,
    borderColor: colors.primary,
  },
  infoCardLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '16px',
    flex: 1,
  },
  infoCardIcon: {
    width: '48px',
    height: '48px',
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  infoCardIconText: {
    fontSize: '24px',
  },
  infoCardDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  infoCardTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
  },
  infoCardSubtitle: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: 0,
    lineHeight: '1.4',
  },
  chevronIcon: {
    fontSize: '24px',
    color: colors.textSecondary,
    marginLeft: '16px',
  },
  checkoutSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    position: 'sticky',
    top: '90px',
    height: 'fit-content',
    alignSelf: 'flex-start',
  },
  orderSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    height: 'fit-content',
  },
  placeOrderButton: {
    width: '100%',
    padding: '16px',
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: borderRadius.md,
    fontSize: '18px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '24px',
    transition: 'all 0.2s ease',
  },
  placeOrderButtonHover: {
    backgroundColor: '#053080',
    transform: 'scale(1.02)',
  },
  placeOrderButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  addressModal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  addressModalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    width: '100%',
    maxWidth: '600px',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
  },
  addressModalHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px 24px',
    borderBottom: `1px solid ${colors.borderLight}`,
  },
  addressModalTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: 0,
  },
  addressModalClose: {
    fontSize: '24px',
    color: colors.textSecondary,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    padding: '4px 8px',
  },
  addressModalBody: {
    padding: '24px',
    overflowY: 'auto',
    maxHeight: 'calc(80vh - 80px)',
  },
  addressCard: {
    padding: '20px',
    border: `2px solid ${colors.borderLight}`,
    borderRadius: borderRadius.md,
    marginBottom: '16px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    position: 'relative',
  },
  addressCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.gray50,
  },
  addressCardName: {
    fontSize: '18px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: '0 0 8px 0',
  },
  addressCardPhone: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: '0 0 8px 0',
  },
  addressCardAddress: {
    fontSize: '14px',
    color: colors.textPrimary,
    lineHeight: '1.6',
    margin: '0 0 4px 0',
  },
  addressCardCountry: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: '8px 0 0 0',
  },
  defaultBadge: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    backgroundColor: colors.primary,
    color: colors.white,
    padding: '4px 12px',
    borderRadius: borderRadius.sm,
    fontSize: '12px',
    fontWeight: '600',
  },
  defaultBadgeText: {
    color: colors.white,
  },
  selectedIndicator: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedIndicatorText: {
    color: colors.white,
    fontSize: '16px',
    fontWeight: 'bold',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: colors.textSecondary,
  },
  emptyStateIcon: {
    fontSize: '64px',
    marginBottom: '16px',
  },
  emptyStateText: {
    fontSize: '18px',
    margin: 0,
  },
  addressFormContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  formLabel: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: '8px',
  },
  formInput: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '16px',
    border: `1px solid ${colors.borderLight}`,
    borderRadius: borderRadius.md,
    backgroundColor: colors.white,
    color: colors.textPrimary,
    boxSizing: 'border-box',
  },
  formInputError: {
    borderColor: '#ef4444',
  },
  formTextarea: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '16px',
    border: `1px solid ${colors.borderLight}`,
    borderRadius: borderRadius.md,
    backgroundColor: colors.white,
    color: colors.textPrimary,
    boxSizing: 'border-box',
    resize: 'vertical',
    fontFamily: 'inherit',
    minHeight: '80px',
  },
  formError: {
    color: '#ef4444',
    fontSize: '12px',
    marginTop: '4px',
    margin: '4px 0 0 0',
  },
  formActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
  },
  formButton: {
    flex: 1,
    padding: '14px 24px',
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: borderRadius.md,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  formButtonSecondary: {
    padding: '14px 24px',
    backgroundColor: 'transparent',
    color: colors.textSecondary,
    border: `1px solid ${colors.borderLight}`,
    borderRadius: borderRadius.md,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
};

