// Order History & Details Page Styles - Desktop Design
import { colors, borderRadius, spacing } from './theme';

// Re-export colors for convenience
export { colors };

export const orderStyles = {
  orderPageContainer: {
    paddingTop: '70px', // Account for fixed top navigation
    minHeight: '100vh',
    backgroundColor: colors.backgroundLight,
  },
  orderHeader: {
    backgroundColor: colors.primary,
    padding: '24px 0',
    marginBottom: '32px',
  },
  orderHeaderContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
  },
  orderHeaderTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: colors.white,
    margin: 0,
    textAlign: 'center',
  },
  orderContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px 40px',
  },
  orderCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    marginBottom: '20px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
    border: `1px solid ${colors.borderLight}`,
  },
  orderCardHover: {
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    transform: 'translateY(-2px)',
    borderColor: colors.primary,
  },
  orderCardHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${colors.borderLight}`,
  },
  orderNumber: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: 0,
  },
  orderDate: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: '4px 0 0 0',
  },
  orderStatusBadge: {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: borderRadius.sm,
    fontSize: '13px',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  orderItemsPreview: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '20px',
  },
  orderItemPreview: {
    display: 'flex',
    flexDirection: 'row',
    gap: '12px',
    alignItems: 'center',
  },
  orderItemImage: {
    width: '60px',
    height: '80px',
    borderRadius: borderRadius.sm,
    objectFit: 'cover',
    backgroundColor: colors.gray100,
    flexShrink: 0,
  },
  orderItemImagePlaceholder: {
    width: '60px',
    height: '80px',
    borderRadius: borderRadius.sm,
    backgroundColor: colors.gray100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    color: colors.gray400,
    flexShrink: 0,
  },
  orderItemDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  orderItemTitle: {
    fontSize: '15px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
    lineHeight: '1.4',
  },
  orderItemQuantity: {
    fontSize: '13px',
    color: colors.textSecondary,
    margin: 0,
  },
  orderCardFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '16px',
    borderTop: `1px solid ${colors.borderLight}`,
  },
  orderTotal: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.primary,
    margin: 0,
  },
  viewDetailsButton: {
    padding: '10px 20px',
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: borderRadius.md,
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  viewDetailsButtonHover: {
    backgroundColor: '#053080',
    transform: 'scale(1.05)',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    textAlign: 'center',
  },
  emptyStateIcon: {
    fontSize: '64px',
    marginBottom: '20px',
  },
  emptyStateTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 12px 0',
  },
  emptyStateSubtitle: {
    fontSize: '16px',
    color: colors.textSecondary,
    margin: 0,
  },
  // Order Details Styles
  orderDetailsCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    marginBottom: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  orderDetailsNumber: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 20px 0',
  },
  orderDetailsInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  orderDetailsRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderDetailsLabel: {
    fontSize: '15px',
    color: colors.textSecondary,
    fontWeight: '500',
  },
  orderDetailsValue: {
    fontSize: '15px',
    color: colors.textPrimary,
    fontWeight: '500',
  },
  orderDetailsStatusBadge: {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: borderRadius.sm,
    fontSize: '13px',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  orderItemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  orderItemCard: {
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
    padding: '16px',
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.borderLight}`,
  },
  orderItemCardImage: {
    width: '80px',
    height: '100px',
    borderRadius: borderRadius.sm,
    objectFit: 'cover',
    backgroundColor: colors.gray100,
    flexShrink: 0,
  },
  orderItemCardImagePlaceholder: {
    width: '80px',
    height: '100px',
    borderRadius: borderRadius.sm,
    backgroundColor: colors.gray100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    color: colors.gray400,
    flexShrink: 0,
  },
  orderItemCardDetails: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  orderItemCardTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
  },
  orderItemCardInfo: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: 0,
  },
  orderItemCardPrice: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: colors.primary,
    alignSelf: 'flex-end',
  },
  shippingAddressCard: {
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    padding: '20px',
    marginTop: '16px',
  },
  shippingAddressTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: '0 0 12px 0',
  },
  shippingAddressText: {
    fontSize: '14px',
    color: colors.textSecondary,
    lineHeight: '1.6',
    margin: 0,
  },
  paymentInfoCard: {
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    padding: '20px',
    marginTop: '16px',
  },
  paymentInfoTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: '0 0 12px 0',
  },
  paymentInfoText: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: '4px 0',
  },
  refreshButton: {
    padding: '12px 24px',
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: borderRadius.md,
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    marginTop: '16px',
  },
  refreshButtonHover: {
    backgroundColor: '#053080',
  },
};

