// Profile Page Styles - Desktop Design
import { colors, borderRadius, spacing } from './theme';

// Re-export colors for convenience
export { colors };

export const profileStyles = {
  profilePageContainer: {
    paddingTop: '70px', // Account for fixed top navigation
    minHeight: '100vh',
    backgroundColor: colors.backgroundLight,
  },
  profileHeader: {
    backgroundColor: colors.primary,
    padding: '24px 0',
    marginBottom: '32px',
  },
  profileHeaderContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px',
  },
  profileHeaderTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: colors.white,
    margin: 0,
    textAlign: 'center',
  },
  profileContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 24px 40px',
  },
  profileSummary: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '40px',
    padding: '32px',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  profilePictureContainer: {
    position: 'relative',
    marginBottom: '20px',
  },
  profilePicture: {
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: `4px solid ${colors.primary}`,
    backgroundColor: colors.gray100,
  },
  profilePicturePlaceholder: {
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    backgroundColor: colors.gray200,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '64px',
    color: colors.gray500,
    border: `4px solid ${colors.primary}`,
  },
  editProfileButton: {
    position: 'absolute',
    bottom: '8px',
    right: '8px',
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    backgroundColor: colors.active,
    border: `3px solid ${colors.white}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  editProfileButtonHover: {
    backgroundColor: '#053080',
    transform: 'scale(1.1)',
  },
  editProfileButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  editIcon: {
    fontSize: '20px',
    color: colors.white,
  },
  userName: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 8px 0',
    textAlign: 'center',
  },
  userEmail: {
    fontSize: '16px',
    color: colors.textSecondary,
    margin: 0,
    textAlign: 'center',
  },
  sectionContainer: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    marginBottom: '24px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },
  sectionTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 20px 0',
    paddingBottom: '16px',
    borderBottom: `2px solid ${colors.borderLight}`,
  },
  optionItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    marginBottom: '12px',
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: `1px solid ${colors.borderLight}`,
  },
  optionItemHover: {
    backgroundColor: colors.gray100,
    borderColor: colors.primary,
    transform: 'translateX(4px)',
  },
  optionItemLast: {
    marginBottom: 0,
  },
  optionLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '16px',
    flex: 1,
  },
  optionIconContainer: {
    width: '48px',
    height: '48px',
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  optionIcon: {
    fontSize: '24px',
  },
  optionTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    flex: 1,
  },
  optionTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
  },
  optionSubtitle: {
    fontSize: '14px',
    color: colors.textSecondary,
    margin: 0,
  },
  chevronIcon: {
    fontSize: '24px',
    color: colors.textSecondary,
    marginLeft: '16px',
  },
  logoutSection: {
    marginTop: '32px',
    marginBottom: '40px',
  },
  logoutButton: {
    width: '100%',
    padding: '16px 24px',
    backgroundColor: colors.accent,
    borderRadius: borderRadius.md,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
  },
  logoutButtonHover: {
    backgroundColor: colors.gray200,
    transform: 'scale(1.02)',
  },
  logoutButtonContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logoutIconContainer: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutIcon: {
    fontSize: '18px',
  },
  logoutButtonText: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: colors.primary,
    margin: 0,
  },
  imagePickerModal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  imagePickerModalContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '24px',
    maxWidth: '400px',
    width: '100%',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
  },
  imagePickerModalTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    margin: '0 0 20px 0',
    textAlign: 'center',
  },
  imagePickerOption: {
    padding: '16px',
    marginBottom: '12px',
    backgroundColor: colors.gray50,
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.borderLight}`,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    textAlign: 'center',
  },
  imagePickerOptionHover: {
    backgroundColor: colors.primary,
    color: colors.white,
  },
  imagePickerOptionText: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    margin: 0,
  },
  imagePickerOptionCancel: {
    backgroundColor: colors.gray200,
    marginBottom: 0,
  },
  imagePickerOptionCancelText: {
    color: colors.textSecondary,
  },
  fileInput: {
    display: 'none',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
  },
};

