// Search Screen Styles
import { colors, borderRadius } from './theme';

export const searchStyles = {
  searchMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
    overflowY: 'auto',
    paddingTop: '20px',
  },
  searchPageTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: '8px',
    textAlign: 'center',
    margin: 0,
  },
  searchPageSubtitle: {
    fontSize: '16px',
    color: colors.textSecondary,
    marginBottom: '32px',
    textAlign: 'center',
    lineHeight: '24px',
  },
  searchModeToggle: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    backgroundColor: colors.gray100,
    borderRadius: borderRadius.md,
    padding: '4px',
    marginBottom: '32px',
  },
  searchModeButton: {
    flex: 1,
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.sm,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    border: 'none',
    backgroundColor: 'transparent',
    fontSize: '16px',
    fontWeight: '600',
    color: colors.gray700,
  },
  searchModeButtonActive: {
    backgroundColor: colors.white,
    color: colors.primary,
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  searchCodeContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  searchCodeInputWrapper: {
    position: 'relative',
    width: '100%',
  },
  searchCodeInput: {
    width: '100%',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    paddingRight: '48px',
    fontSize: '18px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.background,
    color: colors.textPrimary,
    outline: 'none',
    boxSizing: 'border-box',
  },
  searchLoadingIndicator: {
    position: 'absolute',
    right: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: '20px',
  },
  searchDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderLight,
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    zIndex: 1000,
    marginTop: '4px',
    maxHeight: '400px',
    overflowY: 'auto',
  },
  searchDropdownItem: {
    paddingTop: '20px',
    paddingBottom: '20px',
    paddingLeft: '24px',
    paddingRight: '24px',
    minHeight: '80px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.borderLight,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    backgroundColor: 'transparent',
    borderLeft: 'none',
    borderRight: 'none',
    borderTop: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background-color 0.2s',
  },
  searchDropdownItemHover: {
    backgroundColor: colors.gray50,
  },
  searchDropdownCode: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: '8px',
  },
  searchDropdownName: {
    fontSize: '14px',
    color: colors.textLight,
    lineHeight: '22px',
  },
  searchContinueButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: borderRadius.lg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    fontWeight: 'bold',
    color: colors.white,
    boxShadow: '0 4px 8px rgba(194, 204, 227, 0.3)',
  },
  searchNameContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  searchNameInputWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: '12px',
    width: '100%',
  },
  searchNameInput: {
    flex: 1,
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    paddingRight: '16px',
    fontSize: '16px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.background,
    color: colors.textPrimary,
    outline: 'none',
    boxSizing: 'border-box',
  },
  searchNameButton: {
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '24px',
    paddingRight: '24px',
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    border: 'none',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: '600',
    color: colors.white,
    whiteSpace: 'nowrap',
  },
  searchResultsContainer: {
    marginTop: '24px',
  },
  searchResultsTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: '16px',
    margin: 0,
  },
  searchResultsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  searchResultCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: '20px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderLight,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '100%',
    cursor: 'pointer',
    transition: 'transform 0.2s, box-shadow 0.2s, border-color 0.2s',
    textAlign: 'left',
    borderLeft: 'none',
    borderRight: 'none',
    borderTop: 'none',
  },
  searchResultCardHover: {
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    borderColor: colors.primary,
  },
  searchResultCode: {
    fontSize: '16px',
    fontWeight: '600',
    color: colors.primary,
    marginBottom: '8px',
  },
  searchResultName: {
    fontSize: '16px',
    fontWeight: '500',
    color: colors.textPrimary,
    marginBottom: '4px',
    lineHeight: '24px',
  },
  searchResultBoard: {
    fontSize: '14px',
    color: colors.textSecondary,
    marginTop: '4px',
  },
};


