import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#06429c', // rgb(248, 109, 114)
  accent: '#c2cce3', // Teal color for active states
  active: '#5f9ea0', // Teal color for active states
  background: '#ffffff',
  backgroundLight: '#ffffff',
  backgroundDark: '#112120',
  contentLight: '#112120',
  contentDark: '#f6f8f8',
  textPrimary: '#000000',
  textSecondary: '#5f9ea0',
  textLight: '#112120',
  textDark: '#f6f8f8',
  inputLight: '#f0f0f0',
  inputDark: '#223130',
  subtleLight: '#e5e7eb',
  subtleDark: '#374151',
  borderLight: '#E5E7EB',
  borderDark: '#374151',
  header: '#f86d72',
  white: '#ffffff',
  black: '#000000',
  gray50: '#f9fafb',
  gray100: '#f3f4f6',
  gray400: '#9ca3af',
  gray500: '#6b7280',
  gray700: '#374151',
  gray800: '#1f2937',
};

export const typography = {
  display: 'Work Sans',
  regular: 'System',
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const borderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  full: 9999,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  header: {
    backgroundColor: colors.primary,
    paddingVertical: 24,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.white,
  },
  mainContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  loginContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  loginTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: 32,
    textAlign: 'center',
  },
  formContainer: {
    gap: 24,
  },
  inputContainer: {
    marginBottom: 0,
  },
  input: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.inputLight,
    color: colors.textLight,
    borderRadius: borderRadius.md,
    fontSize: 16,
    borderWidth: 0,
  },
  inputFocused: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  forgotPasswordContainer: {
    alignItems: 'flex-end',
    marginTop: 8,
  },
  forgotPasswordText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.primary,
  },
  loginButton: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  sendOtpButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  sendOtpButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  sendOtpButtonDisabled: {
    backgroundColor: colors.gray400,
  },
  resendButton: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  resendButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  signUpContainer: {
    marginTop: 32,
    alignItems: 'center',
  },
  signUpText: {
    fontSize: 14,
    color: colors.textLight,
    opacity: 0.8,
  },
  signUpLink: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.primary,
  },
  // Register Screen Styles
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    maxWidth: 400,
    alignSelf: 'center',
    width: '100%',
  },
  backButton: {
    padding: 8,
    marginLeft: -8,
  },
  backButtonText: {
    fontSize: 24,
    color: colors.white,
    fontWeight: 'bold',
  },
  headerSpacer: {
    width: 24,
  },
  registerContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  registerInput: {
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: colors.backgroundLight,
    color: colors.contentLight,
    borderRadius: borderRadius.lg,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.subtleLight,
  },
  registerButton: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  registerButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  legalContainer: {
    marginTop: 16,
    alignItems: 'center',
  },
  legalText: {
    fontSize: 12,
    color: colors.contentLight,
    opacity: 0.7,
    textAlign: 'center',
    lineHeight: 16,
  },
  legalLink: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  // Search Screen Styles
  searchHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  searchHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  searchHeaderSpacer: {
    flex: 1,
  },
  searchHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  closeButton: {
    flex: 1,
    alignItems: 'flex-end',
  },
  closeButtonText: {
    fontSize: 20,
    color: colors.white,
    fontWeight: 'bold',
  },
  searchMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  searchBarContainer: {
    padding: 16,
  },
  searchInputContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchIcon: {
    position: 'absolute',
    left: 12,
    zIndex: 1,
    fontSize: 20,
    color: colors.accent,
  },
  searchInput: {
    width: '100%',
    paddingLeft: 40,
    paddingRight: 16,
    paddingVertical: 12,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
    color: colors.textLight,
    fontSize: 16,
  },
  popularSchoolsContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  popularSchoolsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: 8,
  },
  schoolsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  schoolCard: {
    width: '48%',
    padding: 16,
    marginBottom: 16,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
  },
  schoolCardText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textLight,
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 8,
  },
  schoolLogo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginBottom: 8,
  },
  // Bottom Navigation Styles
  bottomNavigation: {
    backgroundColor: colors.backgroundLight,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    position: 'sticky',
    bottom: 0,
  },
  bottomNavContent: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 64,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  bottomNavIcon: {
    fontSize: 24,
    marginBottom: 4,
    color: colors.textLight,
    opacity: 0.7,
  },
  bottomNavIconActive: {
    color: colors.accent,
    opacity: 1,
  },
  bottomNavLabel: {
    fontSize: 12,
    color: colors.textLight,
    opacity: 0.7,
  },
  bottomNavLabelActive: {
    color: colors.accent,
    fontWeight: '700',
    opacity: 1,
  },
  bottomNavSpacer: {
    height: 0,
    backgroundColor: colors.backgroundLight,
  },
  // Login Screen Search Button
  searchButton: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    marginTop: 16,
  },
  searchButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  // Home Screen Styles
  homeHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  homeHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  homeLogoContainer: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  homeLogoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
  },
  homeHeaderTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
  homeHeaderSubtitle: {
    fontSize: 14,
    color: colors.white,
    opacity: 0.9,
  },
  homeHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  homeHeaderIcon: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeHeaderIconText: {
    fontSize: 24,
    color: colors.white,
  },
  homeMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  homeBannerContainer: {
    width: '100%',
    height: 200,
    marginBottom: 0,
    backgroundColor: colors.gray100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeBannerImage: {
    width: 400,
    height: 200,
    resizeMode: 'cover',
  },
  homeBannerLoading: {
    width: 400,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.gray100,
  },
  homeTextBanner: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  homeTextBannerText: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
    textAlign: 'center',
  },
  homeSection: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  homeSectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  homeCardsRow: {
    flexDirection: 'row',
    gap: 16,
  },
  homeCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 140,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  homeCardIconContainer: {
    marginBottom: 12,
  },
  homeCardIcon: {
    fontSize: 48,
  },
  homeCardText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primary,
    textAlign: 'center',
  },
  searchIconButton: {
    padding: 8,
  },
  searchIconButtonText: {
    fontSize: 24,
    color: colors.white,
  },
  welcomeSection: {
    padding: 20,
    backgroundColor: colors.backgroundLight,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: 8,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: colors.textLight,
    opacity: 0.7,
    lineHeight: 22,
  },
  quickActionsSection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textLight,
    marginBottom: 16,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  quickActionCard: {
    width: '48%',
    backgroundColor: colors.backgroundLight,
    padding: 20,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  quickActionIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  quickActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textLight,
    textAlign: 'center',
  },
  recentActivitySection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  activityCard: {
    backgroundColor: colors.backgroundLight,
    padding: 20,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  activityText: {
    fontSize: 16,
    color: colors.textLight,
    opacity: 0.7,
    textAlign: 'center',
    lineHeight: 22,
  },
  // School Code Screen Styles
  schoolCodeHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  schoolCodeHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  schoolCodeMainContent: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  schoolCodeContainer: {
    alignItems: 'center',
  },
  schoolCodeTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  schoolCodeSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 32,
    textAlign: 'center',
    lineHeight: 22,
  },
  schoolCodeInputContainer: {
    width: '100%',
    position: 'relative',
    marginBottom: 32,
  },
  schoolCodeInput: {
    width: '100%',
    height: 56,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 18,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.background,
    color: colors.textPrimary,
  },
  dropdown: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1000,
    paddingVertical: 2,
  },
  dropdownScroll: {
    maxHeight: 400,
  },
  dropdownItem: {
    paddingVertical: 20,
    paddingHorizontal: 24,
    minHeight: 100,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    justifyContent: 'center',
  },
  dropdownItemCode: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  dropdownItemName: {
    fontSize: 14,
    color: colors.textLight,
    lineHeight: 22,
  },
  continueButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accent,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  continueButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Cart Screen Styles
  cartHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cartHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  cartMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  cartContent: {
    padding: 16,
  },
  cartSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  cartItemsContainer: {
    gap: 16,
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  bookImage: {
    width: 64,
    height: 80,
    borderRadius: borderRadius.md,
  },
  itemDetails: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  itemPrice: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  quantityButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: `${colors.accent}20`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.accent,
  },
  quantityText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    minWidth: 20,
    textAlign: 'center',
  },
  orderSummaryContainer: {
    marginTop: 32,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  orderSummaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  orderSummaryDetails: {
    gap: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  summaryTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    marginTop: 8,
  },
  summaryTotalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  summaryTotalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  placeOrderContainer: {
    backgroundColor: colors.backgroundLight,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
  },
  placeOrderButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeOrderButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Profile Screen Styles
  profileHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  profileHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileHeaderSpacer: {
    flex: 1,
  },
  profileHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  settingsButton: {
    padding: 8,
  },
  settingsIcon: {
    fontSize: 24,
    color: colors.white,
  },
  profileMainContent: {
    flex: 1,
    backgroundColor: colors.background,
  },
  profileContent: {
    padding: 16,
  },
  profileSummary: {
    alignItems: 'center',
    marginBottom: 32,
  },
  profilePictureContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  profilePicture: {
    width: 128,
    height: 128,
    borderRadius: 64,
  },
  editButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: colors.active,
    borderRadius: 20,
    padding: 8,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editIcon: {
    fontSize: 16,
    color: colors.white,
  },
  userName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 4,
  },
  userEmail: {
    fontSize: 16,
    color: colors.active,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    marginBottom: 8,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.gray50,
  },
  optionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  optionIconContainer: {
    backgroundColor: `${colors.active}20`,
    padding: 12,
    borderRadius: borderRadius.lg,
    marginRight: 16,
  },
  optionIcon: {
    fontSize: 20,
    color: colors.active,
  },
  optionTextContainer: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.gray700,
  },
  optionSubtitle: {
    fontSize: 14,
    color: colors.gray500,
    marginTop: 2,
  },
  chevronIcon: {
    fontSize: 20,
    color: colors.gray400,
    fontWeight: 'bold',
  },
  // Logout Button Styles
  logoutSection: {
    marginTop: 16,
  },
  logoutButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    padding: 16,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  logoutButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutIconContainer: {
    marginRight: 12,
  },
  logoutIcon: {
    fontSize: 20,
    color: colors.white,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.white,
  },
  // Image Picker Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    marginBottom: 12,
    alignItems: 'center',
  },
  modalOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  modalCancel: {
    backgroundColor: colors.gray100,
  },
  modalCancelText: {
    color: colors.textPrimary,
  },
  // Shipping Addresses Screen Styles
  addAddressButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    marginBottom: 24,
  },
  addAddressButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  addressesList: {
    gap: 16,
  },
  addressCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    position: 'relative',
  },
  defaultBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
  },
  defaultBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '600',
  },
  addressCardContent: {
    marginBottom: 12,
  },
  addressCardName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  addressCardPhone: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  addressCardAddress: {
    fontSize: 14,
    color: colors.textLight,
    lineHeight: 20,
    marginBottom: 4,
  },
  addressCardCountry: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  addressCardActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  addressActionButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.gray50,
  },
  addressActionButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  addressEditButton: {
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  addressEditButtonText: {
    color: colors.primary,
  },
  addressDeleteButton: {
    borderColor: '#e74c3c',
    backgroundColor: colors.white,
  },
  addressDeleteButtonText: {
    color: '#e74c3c',
  },
  addressModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
    maxHeight: '90%',
    flex: 1,
  },
  addressModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  addressModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  modalCloseButton: {
    fontSize: 24,
    color: colors.textSecondary,
    fontWeight: 'bold',
  },
  addressModalBody: {
    padding: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.borderLight,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxCheckmark: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontSize: 16,
    color: colors.textPrimary,
  },
  saveAddressButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    marginTop: 8,
  },
  saveAddressButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  // Address Selection Modal Styles
  addressSelectionModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
    maxHeight: '90%',
    flex: 1,
  },
  addressSelectionModalBody: {
    padding: 20,
  },
  addressSelectionCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: 16,
    borderWidth: 2,
    borderColor: colors.borderLight,
    marginBottom: 12,
    position: 'relative',
  },
  addressSelectionCardSelected: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}10`,
  },
  addressSelectionCardContent: {
    marginRight: 40,
  },
  addressSelectionCardName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  addressSelectionCardPhone: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  addressSelectionCardAddress: {
    fontSize: 14,
    color: colors.textLight,
    lineHeight: 20,
    marginBottom: 4,
  },
  addressSelectionCardCountry: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  selectedIndicator: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedIndicatorText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Checkout Screen Styles
  checkoutHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkoutHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  checkoutMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  checkoutContent: {
    padding: 16,
    gap: 24,
  },
  checkoutSection: {
    marginBottom: 0,
  },
  checkoutSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  orderItemsContainer: {
    gap: 16,
  },
  orderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  orderItemImage: {
    width: 64,
    height: 64,
    borderRadius: borderRadius.lg,
  },
  orderItemDetails: {
    flex: 1,
  },
  orderItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  orderItemQuantity: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  orderItemPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  priceBreakdown: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 8,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  priceLabel: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  priceValue: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  priceTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  priceTotalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  priceTotalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  infoCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  infoCardIcon: {
    marginRight: 16,
  },
  infoCardIconText: {
    fontSize: 32,
    color: colors.textSecondary,
  },
  infoCardDetails: {
    flex: 1,
  },
  infoCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  infoCardSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  placeOrderContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    backgroundColor: colors.backgroundLight,
  },
  placeOrderButton: {
    width: '100%',
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeOrderButtonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  // Order History Screen Styles
  orderHistoryHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  orderHistoryHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  orderHistoryHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  orderHistoryMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  orderHistoryContent: {
    padding: 16,
  },
  orderSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    marginBottom: 24,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  orderSummaryHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  orderSummaryTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  orderNumberText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray800,
  },
  orderDateText: {
    fontSize: 14,
    color: colors.gray500,
  },
  orderStatusText: {
    fontSize: 14,
    color: colors.gray600,
  },
  progressBarContainer: {
    padding: 16,
    position: 'relative',
    height: 40,
  },
  progressBarBackground: {
    position: 'absolute',
    top: 20,
    left: 16,
    right: 16,
    height: 4,
    backgroundColor: colors.gray200,
    borderRadius: 2,
  },
  progressBarFill: {
    position: 'absolute',
    top: 20,
    left: 16,
    height: 4,
    backgroundColor: colors.active,
    borderRadius: 2,
  },
  progressStages: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    height: 40,
  },
  progressStage: {
    alignItems: 'center',
    flex: 1,
    position: 'relative',
  },
  progressDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  progressDotActive: {
    backgroundColor: colors.active,
  },
  progressDotInactive: {
    backgroundColor: colors.gray200,
  },
  progressStageText: {
    fontSize: 12,
    textAlign: 'center',
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
  },
  progressStageTextActive: {
    color: colors.gray800,
  },
  progressStageTextInactive: {
    color: colors.gray400,
  },
  timelineContainer: {
    flexDirection: 'column',
    padding: 16,
    paddingTop: 24,
    marginTop: 50,
    marginBottom: 24,
    position: 'relative',
  },
  timelineSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.gray800,
    marginBottom: 16,
    paddingLeft: 24,
  },
  timelineLine: {
    width: 2,
    backgroundColor: colors.gray200,
    position: 'absolute',
    left: 8,
    top: 0,
    bottom: 0,
  },
  timelineEvent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
    paddingLeft: 24,
  },
  timelineDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: 16,
    marginTop: 2,
    borderWidth: 2,
    borderColor: colors.white,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  timelineDotActive: {
    backgroundColor: colors.active,
  },
  timelineDotInactive: {
    backgroundColor: colors.gray300,
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.gray800,
    marginBottom: 4,
  },
  timelineTime: {
    fontSize: 14,
    color: colors.gray500,
    marginBottom: 4,
  },
  timelineDescription: {
    fontSize: 14,
    color: colors.gray600,
    lineHeight: 20,
  },
  viewOrderDetailsButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  viewOrderDetailsButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Order Details Screen Styles
  orderDetailsHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  orderDetailsHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  orderDetailsHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  orderDetailsMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  orderDetailsContent: {
    padding: 16,
  },
  orderSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: 24,
    marginBottom: 24,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  orderDetailsNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 16,
  },
  orderDetailsInfo: {
    gap: 12,
  },
  orderDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderDetailsLabel: {
    fontSize: 14,
    color: colors.gray500,
  },
  orderDetailsValue: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.gray700,
  },
  orderDetailsStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
  },
  orderDetailsStatusText: {
    fontSize: 14,
    fontWeight: '500',
  },
  orderDetailsItemsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  orderDetailsItemsList: {
    gap: 16,
  },
  orderDetailsItemCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  orderDetailsItemImage: {
    width: 64,
    height: 80,
    borderRadius: borderRadius.sm,
    marginRight: 16,
  },
  orderDetailsItemContent: {
    flex: 1,
    marginRight: 16,
  },
  orderDetailsItemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 4,
  },
  orderDetailsItemQuantity: {
    fontSize: 14,
    color: colors.gray500,
  },
  orderDetailsItemPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.gray800,
  },
  // Add Student Screen Styles
  addStudentHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addStudentHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  addStudentHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  addStudentMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  addStudentContent: {
    padding: 16,
    gap: 16,
  },
  formFieldContainer: {
    gap: 4,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.gray700,
  },
  formInput: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.lg,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.gray800,
  },
  formSelect: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: borderRadius.lg,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  formSelectText: {
    fontSize: 16,
    color: colors.gray800,
  },
  formSelectPlaceholder: {
    color: colors.gray500,
  },
  formSelectArrow: {
    fontSize: 12,
    color: colors.gray500,
  },
  addStudentButtonContainer: {
    padding: 16,
    backgroundColor: colors.backgroundLight,
  },
  addStudentButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addStudentButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Students Screen Styles
  studentsHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  studentsHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  studentsHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  studentsMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  studentsContent: {
    padding: 16,
    gap: 16,
  },
  studentCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  studentImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  studentInfo: {
    flex: 1,
  },
  studentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 4,
  },
  studentDetails: {
    fontSize: 14,
    color: colors.gray600,
  },
  studentChevron: {
    fontSize: 18,
    color: colors.gray400,
  },
  studentsAddStudentButtonContainer: {
    padding: 16,
    backgroundColor: colors.backgroundLight,
  },
  studentsAddStudentButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: borderRadius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  studentsAddStudentButtonIcon: {
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  studentsAddStudentButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Past Orders Screen Styles
  pastOrdersHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  pastOrdersHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  pastOrdersHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    flex: 1,
    textAlign: 'center',
  },
  pastOrdersMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  pastOrdersContent: {
    padding: 16,
  },
  pastOrdersTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 16,
  },
  ordersList: {
    gap: 12,
  },
  orderItem: {
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: borderRadius.lg,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  orderItemContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  orderItemLeft: {
    flex: 1,
  },
  orderNumberText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.gray800,
    marginBottom: 4,
  },
  orderDateText: {
    fontSize: 14,
    color: colors.accent,
    marginBottom: 8,
  },
  orderStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: borderRadius.full,
    alignSelf: 'flex-start',
  },
  orderStatusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  orderItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  orderAmountText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.gray800,
  },
  chevronIcon: {
    fontSize: 20,
    color: colors.accent,
    fontWeight: 'bold',
  },
  // Manage Grades Screen Styles
  manageGradesHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  manageGradesHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  manageGradesHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  manageGradesMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  manageGradesToolbar: {
    flexDirection: 'row',
    padding: 16,
    alignItems: 'center',
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  manageGradesSearchContainer: {
    flex: 1,
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  manageGradesSearchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 40,
    paddingRight: 16,
    backgroundColor: colors.inputLight,
    borderRadius: borderRadius.md,
    fontSize: 14,
    color: colors.textLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  manageGradesSearchIcon: {
    position: 'absolute',
    left: 12,
    fontSize: 16,
    color: colors.gray500,
  },
  manageGradesAddButton: {
    backgroundColor: '#ffc107',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: borderRadius.md,
  },
  manageGradesAddButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  manageGradesItemsPerPageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  manageGradesItemsPerPageLabel: {
    fontSize: 14,
    color: colors.gray700,
  },
  manageGradesItemsPerPageSelect: {
    flexDirection: 'row',
    marginHorizontal: 8,
  },
  manageGradesItemsPerPageOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.white,
    marginRight: 4,
  },
  manageGradesItemsPerPageOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  manageGradesItemsPerPageOptionText: {
    fontSize: 14,
    color: colors.gray700,
  },
  manageGradesItemsPerPageOptionTextActive: {
    color: colors.white,
    fontWeight: '600',
  },
  manageGradesContent: {
    flex: 1,
  },
  manageGradesLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  manageGradesLoadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.gray500,
  },
  manageGradesEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  manageGradesEmptyText: {
    fontSize: 16,
    color: colors.gray500,
    textAlign: 'center',
  },
  manageGradesTable: {
    backgroundColor: colors.white,
  },
  manageGradesTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#36b9cc',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
  },
  manageGradesTableHeaderCell: {
    paddingHorizontal: 8,
  },
  manageGradesTableHeaderText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
    letterSpacing: 0.5,
  },
  manageGradesTableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.white,
  },
  manageGradesTableCell: {
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  manageGradesTableCellText: {
    fontSize: 14,
    color: colors.gray800,
  },
  manageGradesTableCellSchool: {
    fontSize: 12,
    color: colors.gray600,
    lineHeight: 18,
  },
  manageGradesTableActionsCell: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  manageGradesEditButton: {
    backgroundColor: colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: borderRadius.sm,
    marginRight: 8,
  },
  manageGradesEditButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '600',
  },
  manageGradesDeleteButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: borderRadius.sm,
  },
  manageGradesDeleteButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '600',
  },
  manageGradesPagination: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  manageGradesPaginationInfo: {
    flex: 1,
  },
  manageGradesPaginationText: {
    fontSize: 14,
    color: colors.gray700,
  },
  manageGradesPaginationControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  manageGradesPaginationButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.white,
    minWidth: 60,
    alignItems: 'center',
  },
  manageGradesPaginationPageButton: {
    minWidth: 40,
    marginHorizontal: 2,
  },
  manageGradesPaginationButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  manageGradesPaginationButtonDisabled: {
    backgroundColor: colors.gray100,
    borderColor: colors.borderLight,
    opacity: 0.5,
  },
  manageGradesPaginationButtonText: {
    fontSize: 14,
    color: colors.gray700,
    fontWeight: '500',
  },
  manageGradesPaginationButtonTextActive: {
    color: colors.white,
    fontWeight: '600',
  },
  manageGradesPaginationButtonTextDisabled: {
    color: colors.gray400,
  },
  // Upsert Grade Screen Styles
  upsertGradeHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  upsertGradeHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  upsertGradeHeaderTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.white,
    textAlign: 'center',
    flex: 1,
  },
  upsertGradeMainContent: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  upsertGradeContent: {
    padding: 16,
  },
  upsertGradeLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  upsertGradeLoadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.gray500,
  },
  upsertGradeSchoolSelectContainer: {
    marginTop: 8,
  },
  upsertGradeSchoolOption: {
    padding: 16,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.borderLight,
    backgroundColor: colors.white,
    marginBottom: 12,
  },
  upsertGradeSchoolOptionSelected: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}10`,
  },
  upsertGradeSchoolOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  upsertGradeSchoolOptionRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.borderLight,
    backgroundColor: colors.white,
    marginRight: 12,
  },
  upsertGradeSchoolOptionRadioSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  upsertGradeSchoolOptionText: {
    flex: 1,
    fontSize: 14,
    color: colors.gray700,
    lineHeight: 20,
  },
  upsertGradeSchoolOptionTextSelected: {
    color: colors.primary,
    fontWeight: '600',
  },
  upsertGradeButtonContainer: {
    padding: 16,
    backgroundColor: colors.backgroundLight,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  upsertGradeSubmitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  upsertGradeSubmitButtonDisabled: {
    opacity: 0.6,
  },
  upsertGradeSubmitButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
