steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_API_BASE_URL=${_REACT_APP_API_BASE_URL}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/vidyarthi-website:$SHORT_SHA'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/vidyarthi-website:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/vidyarthi-website:$SHORT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vidyarthi-website'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/vidyarthi-website:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'

substitutions:
  _REACT_APP_API_BASE_URL: 'https://vidyarthi-backend-594708558503.us-central1.run.app'

images:
  - 'gcr.io/${PROJECT_ID}/vidyarthi-website:$SHORT_SHA'
  - 'gcr.io/${PROJECT_ID}/vidyarthi-website:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY





